/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-canvas': '#F8FAFC',
        'canvas-base': '#F8FAFC',
        'surface-card': '#FFFFFF',
        'surface-lowest': '#FFFFFF',
        'surface-container': '#F1F5F9',
        'surface-container-high': '#E2E8F0',
        'border-rule': '#E2E8F0',
        'text-primary': '#0F172A',
        'text-muted': '#64748B',
        'primary': '#00236F',
        'primary-container': '#1E3A8A',
        'on-primary': '#FFFFFF',
        'on-surface': '#0F172A',
        'state-success': '#16A34A',
        'timer-warning': '#D97706',
        'timer-critical': '#DC2626',
        'secondary-container': '#2563EB',
        // candidate-scorecard.html token aliases
        canvas: '#F8FAFC',
        card: '#FFFFFF',
        borderRule: '#E2E8F0',
        primaryText: '#0F172A',
        mutedText: '#64748B',
        success: '#16A34A',
        warning: '#D97706',
        critical: '#DC2626',
        navy: {
          DEFAULT: '#1E3A8A',
          hover: '#172554',
        },
        timer: {
          normal: '#0F172A',
          warning: '#D97706',
          critical: '#DC2626',
        },
      },
      spacing: {
        'unit-1': '4px',
        'unit-2': '8px',
        'unit-3': '12px',
        'unit-4': '16px',
        'unit-5': '20px',
        'unit-6': '24px',
        'unit-8': '32px',
        'unit-10': '40px',
        'unit-12': '48px',
        'unit-16': '64px',
        'admin-gutter': '16px',
        'candidate-max-width': '1040px',
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        display: ['"IBM Plex Sans"', 'sans-serif'],
        'body-default': ['"IBM Plex Sans"', 'sans-serif'],
        'body-compact': ['"IBM Plex Sans"', 'sans-serif'],
        'body-reading': ['"IBM Plex Sans"', 'sans-serif'],
        'label-prominent': ['"IBM Plex Sans"', 'sans-serif'],
        'label-default': ['"IBM Plex Sans"', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
        'timer-display': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'label-default': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-mono': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-compact': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'display': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'timer-display': ['20px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-reading': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'timer-display-compact': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'label-prominent': ['14px', { lineHeight: '18px', fontWeight: '500' }],
        'body-default': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '4px',
        standard: '4px',
        lg: '4px',
        xl: '8px',
      },
      maxWidth: {
        'candidate-max-width': '1040px',
      },
    },
  },
  plugins: [],
}

